name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NAME: 'Test'
          AGE: 'Test'
          ADDRESS: 'Test'
          ZIPCITY: 'Test'
          PHONE: 'Test'