name: Daily surplus vaccine

#on: [push]
on:
  schedule:
    - cron:  '1 0 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_NAME: ${{ secrets.NAME }}
          CYPRESS_AGE: ${{ secrets.AGE }}
          CYPRESS_ADDRESS: ${{ secrets.ADDRESS }}
          CYPRESS_ZIPCITY: ${{ secrets.ZIPCITY }}
          CYPRESS_PHONE: ${{ secrets.PHONE }}