name: Daily surplus vaccine

# on: [push]
on:
  schedule:
    - cron:  '05 00 * * *'

jobs:
  order-surplus-vaccine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Order vaccine
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_NAME_LARS: ${{ secrets.NAME_LARS }}
          CYPRESS_AGE_LARS: ${{ secrets.AGE_LARS }}
          CYPRESS_ADDRESS_LARS: ${{ secrets.ADDRESS_LARS }}
          CYPRESS_ZIPCITY_LARS: ${{ secrets.ZIPCITY_LARS }}
          CYPRESS_PHONE_LARS: ${{ secrets.PHONE_LARS }}
          CYPRESS_NAME_LAERKE: ${{ secrets.NAME_LAERKE }}
          CYPRESS_AGE_LAERKE: ${{ secrets.AGE_LAERKE }}
          CYPRESS_ADDRESS_LAERKE: ${{ secrets.ADDRESS_LAERKE }}
          CYPRESS_ZIPCITY_LAERKE: ${{ secrets.ZIPCITY_LAERKE }}
          CYPRESS_PHONE_LAERKE: ${{ secrets.PHONE_LAERKE }}
          CYPRESS_FROMEMAIL: ${{ secrets.FROMEMAIL }}
          CYPRESS_TOEMAILS: ${{ secrets.TOEMAILS }}
          CYPRESS_EMAILSMTPHOST: ${{ secrets.EMAILSMTPHOST }}
          CYPRESS_EMAILSMTPORT: ${{ secrets.EMAILSMTPORT }}
          CYPRESS_EMAILAUTHUSER: ${{ secrets.EMAILAUTHUSER }}
          CYPRESS_EMAILAUTHPASS: ${{ secrets.EMAILAUTHPASS }}
