name: Cypress Tests

on: [push]
# on:
#   schedule:
#     - cron:  '1 0 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NAME: ${{ secrets.NAME }}
          AGE: ${{ secrets.AGE }}
          ADDRESS: ${{ secrets.ADDRESS }}
          ZIPCITY: ${{ secrets.ZIPCITY }}
          PHONE: ${{ secrets.PHONE }}