name: Daily surplus vaccine

# on: [push]
on:
  schedule:
    - cron:  '58 23 * * *'

jobs:
  order-surplus-vaccine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Order vaccine
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_NAME: 'Mia Bretlau Nybroe'
          CYPRESS_AGE: '28'
          CYPRESS_ADDRESS: 'Bakkesvinget 17'
          CYPRESS_ZIPCITY: '3550 Slangerup'
          CYPRESS_PHONE: '31148212'
